name: deploy LANDING

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Installation des dépendances
        run: npm ci

      - name: Lint et Tests (Optionnel)
        run: npm run test

      - name: Build de l'application
        run: npm run build

      # - name: Déploiement sur GitHub Pages
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: dist/landing-page # À corriger plus tard
      #     branch: gh-pages
